apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-mysql
spec:
  replicas: 2   # this is the self-healing/scaling piece compose couldn't do:
                # if a pod dies, Kubernetes replaces it automatically
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          # Build locally and load into kind with:
          #   docker build -t flask-mysql-demo:stage3 .
          #   kind load docker-image flask-mysql-demo:stage3
          image: flask-mysql-demo:stage3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: flask-config
            - secretRef:
                name: flask-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
